version: '3'

services:
    db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=storage
        - POSTGRES_PASSWORD=storage
        - POSTGRES_DB=storage
      ports:
        - '127.0.0.1:5432:5432'
      volumes:
        - db:/var/lib/postgresql/data
      networks:
        - crcbot
    circles-bot:
      image: ice0nine/telegram-bot
      restart: always
      networks:
        - crcbot
volumes:
  db:
    driver: local
networks:
  crcbot:
