version: '3'

services:
    db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - db:/var/lib/postgresql/data
    circles:
      image: circles-stats-web-proxy:0.0.1-SNAPSHOT